name: docs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v5
      - name: Build
        run: npm install && npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: GitHub Pages deploy
        uses: actions/deploy-pages@v4
